/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest':  '#0e0e0e',
        'surface-container-low':     '#1b1b1b',
        'surface-container':         '#1f1f1f',
        'surface-container-high':    '#2a2a2a',
        'surface-container-highest': '#353535',
        'surface':                   '#131313',
        'surface-variant':           '#353535',
        'surface-bright':            '#393939',
        'on-surface':                '#e2e2e2',
        'on-surface-variant':        '#c4c7c8',
        'on-background':             '#e2e2e2',
        'background':                '#131313',
        'primary':                   '#ffffff',
        'on-primary':                '#2f3131',
        'primary-container':         '#e2e2e2',
        'primary-fixed':             '#e2e2e2',
        'primary-fixed-dim':         '#c6c6c7',
        'outline':                   '#8e9192',
        'outline-variant':           '#444748',
        'error':                     '#ffb4ab',
        'error-container':           '#93000a',
        'on-error':                  '#690005',
        'on-error-container':        '#ffdad6',
        'secondary':                 '#c8c6c5',
        'secondary-container':       '#474746',
        'tertiary':                  '#ffffff',
      },
      fontFamily: {
        'headline-lg':  ['Space Grotesk', 'sans-serif'],
        'headline-md':  ['Space Grotesk', 'sans-serif'],
        'headline-sm':  ['Inter', 'sans-serif'],
        'body-lg':      ['Inter', 'sans-serif'],
        'body-md':      ['Inter', 'sans-serif'],
        'label-lg':     ['Space Grotesk', 'sans-serif'],
        'label-md':     ['JetBrains Mono', 'monospace'],
        'label-sm':     ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['20px', { lineHeight: '24px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-md': ['16px', { lineHeight: '20px', letterSpacing: '0.06em', fontWeight: '700' }],
        'headline-sm': ['14px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-lg':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md':     ['12px', { lineHeight: '17px', fontWeight: '400' }],
        'label-lg':    ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'label-md':    ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '500' }],
        'label-sm':    ['10px', { lineHeight: '12px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.25rem',
        'gutter':   '0.75rem',
        'margin':   '1rem',
      },
    }
  },
  plugins: [],
}
