// Mocks generated by Mockito 5.4.6 from annotations
// in mobile/test/comparison_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i6;
import 'dart:typed_data' as _i8;

import 'package:mobile/models/capability_model.dart' as _i9;
import 'package:mobile/models/experiment_model.dart' as _i3;
import 'package:mobile/models/image_model.dart' as _i7;
import 'package:mobile/models/pipeline_model.dart' as _i2;
import 'package:mobile/services/api_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePipelineRunResponseModel_0 extends _i1.SmartFake
    implements _i2.PipelineRunResponseModel {
  _FakePipelineRunResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRobustnessExperimentModel_1 extends _i1.SmartFake
    implements _i3.RobustnessExperimentModel {
  _FakeRobustnessExperimentModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  void setBaseUrl(String? newUrl) => super.noSuchMethod(
    Invocation.method(#setBaseUrl, [newUrl]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> checkHealth() =>
      (super.noSuchMethod(
            Invocation.method(#checkHealth, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i7.DemoPairModel>> fetchDemoPairs() =>
      (super.noSuchMethod(
            Invocation.method(#fetchDemoPairs, []),
            returnValue: _i6.Future<List<_i7.DemoPairModel>>.value(
              <_i7.DemoPairModel>[],
            ),
          )
          as _i6.Future<List<_i7.DemoPairModel>>);

  @override
  _i6.Future<Map<String, dynamic>> uploadImageBytes(
    _i8.Uint8List? bytes,
    String? filename,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImageBytes, [bytes, filename]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i2.PipelineRunResponseModel> runPipeline(
    String? refId,
    String? movId,
    String? refSensor,
    String? movSensor,
    _i2.PipelineConfigModel? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#runPipeline, [
              refId,
              movId,
              refSensor,
              movSensor,
              config,
            ]),
            returnValue: _i6.Future<_i2.PipelineRunResponseModel>.value(
              _FakePipelineRunResponseModel_0(
                this,
                Invocation.method(#runPipeline, [
                  refId,
                  movId,
                  refSensor,
                  movSensor,
                  config,
                ]),
              ),
            ),
          )
          as _i6.Future<_i2.PipelineRunResponseModel>);

  @override
  _i6.Future<_i3.RobustnessExperimentModel> runRobustnessExperiment(
    String? baseImageId,
    String? experimentType,
    int? steps,
    double? minVal,
    double? maxVal,
    _i2.PipelineConfigModel? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#runRobustnessExperiment, [
              baseImageId,
              experimentType,
              steps,
              minVal,
              maxVal,
              config,
            ]),
            returnValue: _i6.Future<_i3.RobustnessExperimentModel>.value(
              _FakeRobustnessExperimentModel_1(
                this,
                Invocation.method(#runRobustnessExperiment, [
                  baseImageId,
                  experimentType,
                  steps,
                  minVal,
                  maxVal,
                  config,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.RobustnessExperimentModel>);

  @override
  _i6.Future<List<_i9.CapabilityItemModel>> fetchCapabilities() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCapabilities, []),
            returnValue: _i6.Future<List<_i9.CapabilityItemModel>>.value(
              <_i9.CapabilityItemModel>[],
            ),
          )
          as _i6.Future<List<_i9.CapabilityItemModel>>);

  @override
  _i6.Future<Map<String, dynamic>> fetchDemoCompare(String? pairName) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDemoCompare, [pairName]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> fetchFailureCase() =>
      (super.noSuchMethod(
            Invocation.method(#fetchFailureCase, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  String resolveFullUrl(String? endpointOrPath) =>
      (super.noSuchMethod(
            Invocation.method(#resolveFullUrl, [endpointOrPath]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#resolveFullUrl, [endpointOrPath]),
            ),
          )
          as String);
}
