"""Comparison API router for side-by-side results and failure-case screens.

All endpoints are registered under the /api prefix by app/main.py,
so the routes defined here are relative to that prefix:
  POST /api/demo/compare
  GET  /api/demo/failure-case
"""

import json
import math
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Body, HTTPException

from ..config import settings
from ..utils.file_utils import load_json, to_json_serializable

router = APIRouter(tags=["Demo"])


def sanitize_for_json(obj: Any) -> Any:
    """Recursively replace inf/-inf/nan with None for JSON serialization."""
    if isinstance(obj, dict):
        return {k: sanitize_for_json(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [sanitize_for_json(v) for v in obj]
    if isinstance(obj, float):
        if math.isnan(obj) or math.isinf(obj):
            return None
        return obj
    return obj


def _cached_compare_result() -> dict:
    """Read the pre-computed real SIFT-vs-RIFT2 comparison from cache.

    The cache is generated by backend/scripts/compute_and_cache.py which
    runs both methods through the full pipeline on the same demo pair.
    """
    cache_path = settings.BASE_DIR / "data" / "demo" / "compare_result.json"
    if not cache_path.exists():
        raise HTTPException(
            status_code=503,
            detail="Comparison cache is unavailable. Run scripts/compute_and_cache.py first.",
        )
    with open(cache_path, "r", encoding="utf-8") as f:
        return json.loads(f.read())


def _latest_run() -> Path:
    runs = sorted(
        (path for path in settings.OUTPUTS_DIR.iterdir() if path.is_dir()),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    if not runs:
        raise HTTPException(status_code=404, detail="No completed demo run is available")
    return runs[0]


def _fmt(value: Any, pattern: str = "value") -> str:
    """Format a numeric check value for display, handling None and non-finite safely."""
    if value is None:
        return "N/A"
    try:
        f = float(value)
    except (TypeError, ValueError):
        return "N/A"
    if not math.isfinite(f):
        return "N/A"
    if pattern == "ratio" or pattern == "coverage":
        return f"{f:.2f}"
    if pattern == "rmse":
        return f"{f:.1f} px"
    if pattern == "condition":
        return f"{f:.1e}"
    if pattern == "int":
        return str(int(f))
    return f"{f:.2f}"


def _criteria_entry(name, label, checklist, fmt_pattern, default=0.0):
    raw = checklist.get(name, {})
    value = raw.get("value", default)
    return {
        "name": name,
        "label": label,
        "value": value,
        "threshold": raw.get("threshold", default),
        "pass": raw.get("pass", False),
        "display": _fmt(value, fmt_pattern),
    }


@router.post("/compare")
def compare_pipelines(payload: dict = Body(...)):
    """Real comparison: SIFT baseline vs LunarMatch (RIFT2) on the bundled demo pair.

    Both methods are run through the full pipeline by
    scripts/compute_and_cache.py and the results are cached.
    The response reflects actual measured metrics — no hard-coded values.
    """
    cache = _cached_compare_result()
    pair_name = payload.get("pair_name") or cache.get("pair_name", "Pair A: bundled prototype")
    return sanitize_for_json({
        "pair_name": pair_name,
        "provenance": cache.get("provenance", "Measured — both methods run on the same demo pair"),
        "sift": cache["sift"],
        "lunarmatch": cache["lunarmatch"],
    })


@router.get("/failure-case")
def failure_case():
    """Return a structured rejection example for the failure-case demo screen."""
    run_dir = _latest_run()
    quality_path = run_dir / "quality_report.json"
    if not quality_path.exists():
        raise HTTPException(status_code=404, detail="No quality report is available")
    quality = load_json(quality_path)
    reg = quality.get("registration_decision", {})
    checklist = reg.get("checklist", {})
    criteria = [
        _criteria_entry("overlap_ratio", "Overlap ratio", checklist, "coverage", 0.1),
        _criteria_entry("inlier_count", "Inlier count", checklist, "int", 30),
        _criteria_entry("inlier_ratio", "Inlier ratio", checklist, "ratio", 0.15),
        _criteria_entry("spatial_coverage", "Spatial coverage", checklist, "coverage", 0.4),
        _criteria_entry("rmse_pixels", "RMSE", checklist, "rmse", 2.0),
        _criteria_entry("homography_determinant", "Determinant", checklist, None, 0.0),
        _criteria_entry("condition_number_H", "Condition number", checklist, "condition", 1e6),
    ]
    failed = reg.get("failed_criteria", [])
    return sanitize_for_json({
        "decision": reg.get("decision", "REGISTRATION_NOT_RELIABLE"),
        "reason": reg.get("reason", ""),
        "failed_criteria": failed,
        "criteria": criteria,
        "n_inliers": quality.get("n_inliers", 0),
        "n_rejected_refinement": quality.get("subpixel", {}).get("n_rejected_refinement", 0),
        "note": "We return REGISTRATION_NOT_RELIABLE rather than a wrong transform. Downstream users can trust the metric.",
    })